ci: add queries patch to rockspec

diff --git a/.github/workflows/publish-ts-parsers.yml b/.github/workflows/publish-ts-parsers.yml
--- a/.github/workflows/publish-ts-parsers.yml
+++ b/.github/workflows/publish-ts-parsers.yml
@@ -103,6 +103,19 @@ jobs:
             resources
           path: rockspec-template
 
+      - name: Prepare queries patch
+        run: |
+          git clone --depth=1 "git@github.com:nvim-treesitter/nvim-treesitter.git" nvim-treesitter
+          pushd nvim-treesitter
+          checkout main # TODO pin and checkout revision based on nvim-treesitter lockfile
+          popd
+          rm -r queries || true
+          mkdir queries
+          cp -r "nvim-treesitter/parsers/queries/${{ matrix.parsers.lang }}" queries
+          rm -r nvim-treesitter
+          git add queries
+          git -C "$(git rev-parse --show-toplevel)" diff --cached --src-prefix='' --dst-prefix='' > queries.patch
+
       - name: Prepare Rockspec template
         env:
           SOURCES_JSON: ${{ toJson(matrix.parsers.install_info.files) }}
@@ -125,71 +138,72 @@ jobs:
           then
             sed -i 's@location\s=\snil@location = "${{ matrix.parsers.install_info.location }}"@g' rockspec.template
           fi
+          sed -i -e '/PATCH_CONTENT/ {' -e 'r queries.patch' -e 'd' -e '}' rockspec.template
           cat rockspec.template
 
-      - name: Install `luarocks-build-treesitter-parser` Package
-        run: |
-          luarocks --verbose --local --lua-version=5.1 install luarocks-build-treesitter-parser
-
-      - name: Install askalono-cli for license detection
-        uses: baptiste0928/cargo-install@v3
-        with:
-          crate: askalono-cli
-
-      - name: Get SPDX license
-        run: |
-          LICENSE=$(askalono crawl . | sed -n 's/License: \([^ ]*\).*/\1/p' || echo "UNKNOWN")
-          LICENSE_COUNT=$(echo "$LICENSE" | grep -c .)
-          if [ "$LICENSE_COUNT" -eq 1 ]; then
-            echo "License: $LICENSE"
-          else
-            if [ "$LICENSE_COUNT" -eq 0 ]; then
-              echo "Error: No license identified."
-            else
-              echo "Error: Multiple licenses identified."
-            fi
-            LICENSE="UNKNOWN"
-          fi
-          echo "LICENSE=$LICENSE" >> $GITHUB_ENV
-
-      - name: Publish LuaRock (release)
-        uses: nvim-neorocks/luarocks-tag-release@v5
-        if: ${{ env.RELEASE_VERSION != '' }}
-        env:
-          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
-        with:
-          name: ${{ env.PARSER_NAME }}
-          version: ${{ env.RELEASE_VERSION }}
-          summary: tree-sitter parser for ${{ matrix.parsers.lang }}
-          template: "rockspec.template"
-          license: ${{ env.LICENSE }}
-          labels: |
-            neovim
-            tree-sitter
-          extra_luarocks_args: |
-            --namespace=neorocks
-            --force
-
-      - name: Remove generated rockspec
-        if: always()
-        run: |
-          rm "${{ env.PARSER_NAME }}-${{ env.RELEASE_VERSION }}-1.rockspec" \
-           || echo "Nothing to remove."        
-
-      - name: Publish LuaRock (dev)
-        if: always()
-        uses: nvim-neorocks/luarocks-tag-release@v5
-        env:
-          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
-        with:
-          name: ${{ env.PARSER_NAME }}
-          version: 'scm'
-          summary: tree-sitter parser for ${{ matrix.parsers.lang }}
-          template: "rockspec.template"
-          license: ${{ env.LICENSE }}
-          labels: |
-            neovim
-            tree-sitter
-          extra_luarocks_args: |
-            --namespace=neorocks
-            --force
+      # - name: Install `luarocks-build-treesitter-parser` Package
+      #   run: |
+      #     luarocks --verbose --local --lua-version=5.1 install luarocks-build-treesitter-parser
+      #
+      # - name: Install askalono-cli for license detection
+      #   uses: baptiste0928/cargo-install@v3
+      #   with:
+      #     crate: askalono-cli
+      #
+      # - name: Get SPDX license
+      #   run: |
+      #     LICENSE=$(askalono crawl . | sed -n 's/License: \([^ ]*\).*/\1/p' || echo "UNKNOWN")
+      #     LICENSE_COUNT=$(echo "$LICENSE" | grep -c .)
+      #     if [ "$LICENSE_COUNT" -eq 1 ]; then
+      #       echo "License: $LICENSE"
+      #     else
+      #       if [ "$LICENSE_COUNT" -eq 0 ]; then
+      #         echo "Error: No license identified."
+      #       else
+      #         echo "Error: Multiple licenses identified."
+      #       fi
+      #       LICENSE="UNKNOWN"
+      #     fi
+      #     echo "LICENSE=$LICENSE" >> $GITHUB_ENV
+      #
+      # - name: Publish LuaRock (release)
+      #   uses: nvim-neorocks/luarocks-tag-release@v5
+      #   if: ${{ env.RELEASE_VERSION != '' }}
+      #   env:
+      #     LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
+      #   with:
+      #     name: ${{ env.PARSER_NAME }}
+      #     version: ${{ env.RELEASE_VERSION }}
+      #     summary: tree-sitter parser for ${{ matrix.parsers.lang }}
+      #     template: "rockspec.template"
+      #     license: ${{ env.LICENSE }}
+      #     labels: |
+      #       neovim
+      #       tree-sitter
+      #     extra_luarocks_args: |
+      #       --namespace=neorocks
+      #       --force
+      #
+      # - name: Remove generated rockspec
+      #   if: always()
+      #   run: |
+      #     rm "${{ env.PARSER_NAME }}-${{ env.RELEASE_VERSION }}-1.rockspec" \
+      #      || echo "Nothing to remove."        
+      #
+      # - name: Publish LuaRock (dev)
+      #   if: always()
+      #   uses: nvim-neorocks/luarocks-tag-release@v5
+      #   env:
+      #     LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
+      #   with:
+      #     name: ${{ env.PARSER_NAME }}
+      #     version: 'scm'
+      #     summary: tree-sitter parser for ${{ matrix.parsers.lang }}
+      #     template: "rockspec.template"
+      #     license: ${{ env.LICENSE }}
+      #     labels: |
+      #       neovim
+      #       tree-sitter
+      #     extra_luarocks_args: |
+      #       --namespace=neorocks
+      #       --force
